version: '3.8'

services:
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'mydatabaseuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"

  web:
    image: ghcr.io/bennyhinn18/inventory-manager:latest
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  mysql_data: